server:
  port: 8888

spring:
  profiles:
    active: default
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/81quanghuy/cloud_config_Restora.git
          basedir: /opt/cloud-config-repo